server:
  port: 8051
  servlet:
    context-path: /auth_user

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  application:
    name: ead-authuser

logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: debug
    org.hibernate: info

#RestTemplate URI connection between microservices
ead:
  course:
    url: 'http://ead-course'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost