server:
  port: 8052
  servlet:
    context-path: /courses

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: TRACE
    root: info
    org.springframework.web: debug
    org.hibernate: info
